# Generated by Django 3.0 on 2019-12-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrels',
            name='Fur_Color',
        ),
        migrations.AddField(
            model_name='squirrels',
            name='Fur_Colour',
            field=models.CharField(choices=[('black', 'Black'), ('cinnamon', 'Cinnamon'), ('gray', 'Gray')], default='black', help_text='Fur Colour', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='Location',
            field=models.CharField(choices=[('ground plane', ' Ground Plane'), ('above ground', 'Above Ground'), ('other', 'Other')], default='other', help_text='Location', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrels',
            name='Specific_Location',
            field=models.CharField(default='', help_text='Specific Location', max_length=30),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', ''), ('?', '?')], default='', help_text='Age', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Approaches'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Chasing'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Climbing'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Date',
            field=models.DateField(help_text='Date'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Eeating'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Foraging'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Indifferent'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Latitude',
            field=models.FloatField(help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Longitude',
            field=models.FloatField(help_text='Longitude'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Other_Activities',
            field=models.CharField(default=None, help_text='Other activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Running',
            field=models.BooleanField(default=False, help_text='Running'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Runs_from',
            field=models.BooleanField(default=False, help_text='Run from'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=2),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Squirrel_Id',
            field=models.CharField(help_text='Squirrel ID', max_length=30),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Tail_flags',
            field=models.BooleanField(default=False, help_text='Tail Flags'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Tail_twitch',
            field=models.BooleanField(default=False, help_text='Tail Twitch'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='kuk',
            field=models.BooleanField(default=False, help_text='kuk'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='moan',
            field=models.BooleanField(default=False, help_text='moan'),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='quaas',
            field=models.BooleanField(default=False, help_text='quaas'),
        ),
    ]
