# Generated by Django 3.0 on 2019-12-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0002_auto_20191209_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', ''), ('?', '?')], default='', help_text='Age', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Fur_Colour',
            field=models.CharField(choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray')], default='Black', help_text='Fur Colour', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Location',
            field=models.CharField(choices=[('Ground Plane', ' Ground Plane'), ('Above Ground', 'Above Ground'), ('Other', 'Other')], default='Other', help_text='Location', max_length=100),
        ),
    ]
